add min-content on height of task names
Corvimae/pokemon-ranger pull request #33
Opened 2022-12-07 17:49 UTC by zachjamesgreen

Gave height to TaskNames of min-content. It spaces things out more but with the filter it should be fine.
![image](https://user-images.githubusercontent.com/7896916/206256827-395134a1-48f5-403c-90a0-0b57ad598083.png)

2022-12-07 23:12 UTC, Corvimae commented
What does this change from current functionality?

2022-12-08 16:32 UTC, zachjamesgreen commented
on smaller screens the text on the page was overlapping to not be readable
![IMG](https://user-images.githubusercontent.com/49997031/153723793-e5cd8c45-1ec3-4e6f-82cc-0c7a492f9d15.PNG)

2022-12-08 20:20 UTC, Corvimae commented
oh lol yeah that's pretty bad

2022-12-08 20:21 UTC, Corvimae requested changes

2022-12-08 20:21 UTC, Corvimae commented on pages/arceus/research.tsx
> +  height: min-content !important;
Don't use !important

2025-10-16 16:00 UTC, closed without merging